### ISSUE TITLE
undescribable bug

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1076]
```
[ERROR][16:32:18] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][16:32:18] Exception was:
Traceback (most recent call last):

  File "/home/lasse/prog/coala/coalib/coala_main.py", line 130, in run_coala
    nothing_done(log_printer)

  File "/home/lasse/prog/coala/coalib/output/ConsoleInteraction.py", line 61, in nothing_done
    console_printer.print("No existent section was targeted or enabled. "

AttributeError: 'LogPrinter' object has no attribute 'print'
```

**Comment by sils1297** [comment]
ah we need to use a log printer, not a console printer here, is probably easy to fix
