### ISSUE TITLE
Windows: Coala replaces some special caracters to unkown character

### ISSUE THREAD

**Issue by TimSo94** [coala-analyzer/coala#1238]
When I run coala, it replaces some special characters like this:
![coala1](https://cloud.githubusercontent.com/assets/15891199/12530119/e4356bc6-c1d3-11e5-8253-d4b0cc4cab71.png)

When I want to start it a second time, I get these error messages, because it can't handle with the ?-Character:
![coala2](https://cloud.githubusercontent.com/assets/15891199/12530120/eb287504-c1d3-11e5-8134-552705ab9023.png)

**Comment by Makman2** [comment]
Seems to be an internal encoding issue somewhere. cmd uses a special encoding format (something with `cp` and a number) that is not really compatible to unicode that would explain this more or less^^

If you need to work with coala, try to use Powershell, I believe it uses unicode as default^^

I'll investigate this, but I have not that much time now so this could take a while^^

**Comment by sils1297** [comment]
This is not a usability issue, it's a bug in coala. We shouldn't destroy his data like this. @Makman2 are we even sure this doesn't happen on linux?

Scheduling importance to high since this is connected to actual data loss.

@TimSo94 are you free to share the original file where this occurred with us?

**Comment by TimSo94** [comment]
Yes, it happend in 2 files.
In the functions.py in line 75 and line 78 and in the models.py in line 108 and 109.

[pys.zip](https://github.com/coala-analyzer/coala/files/102003/pys.zip)

**Comment by sils1297** [comment]
@TimSo94 we'll try to look into this soon. I hope we can get to fix this till next week.

**Comment by Makman2** [comment]
@TimSo94 could you also provide the `.coafile`? First reproduction on fedora 23 didn't yield an error, my assumed coafile was:
```
[Default]
bears = PEP8Bear
```

**Comment by sils1297** [comment]
Mischa: you could just introduce an error and see if this occurs for now.

**Comment by Makman2** [comment]
Introducing an error (in this case trailing whitespaces) did nothing.
(okay on fedora it marked the completely file as deleted and added, but I assume this is because of CRLF file endings that get completely rewritten when a patch is applied due to pythons universal-newlines conversion)

**Comment by Makman2** [comment]
Currrently I have problems reproducing this on windows since coala doesn't take up the files there...

**Comment by Makman2** [comment]
Confirmed on Windows! Since this error only happened after apply, I believe @TimSo94 you have a setting like `default_actions = PEP8Bear: AutoApplyAction` so coala automatically fixes errors, that's why it replaces directly with these weird signs. After that it can't read them again.

**Comment by Makman2** [comment]
Also this doesn't come from the `PEP8Bear`, the according diff only showed me the error I introduced^^
Looks like the write-back is responsible for this...

**Comment by TimSo94** [comment]
I only have the "Standard" Settings, here:
[Default]
bears = PEP8Bear
files = **/*.py

**Comment by sils1297** [comment]
@Makman2 he applied it manually which does the same thing I guess, makes no difference

**Comment by fneu** [comment]
Looks like Windows doesn't use unicode or utf-8 encoding for text files by default, but rather [ANSI](http://stackoverflow.com/questions/701882/what-is-ansi-format) or `cp1252` encoding by default.

My first guess would be that the problem occurs because we don't specify any encoding when reading or writing files. Looks like we *should*

**Comment by fneu** [comment]
C:\Users\fabia\Downloads\pys>coala -f functions.py models.py -L DEBUG
Executing section Default...
[DEBUG][22:57:32] Running bear PEP8Bear...
[DEBUG][22:57:32] Running bear PEP8Bear...

c:\users\fabia\downloads\pys\models.py
|   1| [ERROR][22:57:33] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][22:57:33] Exception was:
Traceback (most recent call last):

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\pyprint\ColorPrinter.py", line 43, in _print
    return self._print_colored(output, **kwargs)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\pyprint\ConsolePrinter.py", line 27, in _print_colored
    print(colored(output, color), end="")

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 162, in write_and_convert
    self.write_plain_text(text, cursor, start)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\coala_main.py", line 108, in run_coala
    log_printer=log_printer)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\processes\Processing.py", line 547, in execute_section
    log_printer),

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\processes\Processing.py", line 442, in process_queues
    ignore_ranges)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\processes\Processing.py", line 201, in print_result
    print_results(log_printer, section, results, file_dict, file_diff_dict)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\output\ConsoleInteraction.py", line 230, in print_results
    sourcerange)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\output\ConsoleInteraction.py", line 249, in print_affected_lines
    sourcerange)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\coalib\output\ConsoleInteraction.py", line 101, in print_lines
    color=HIGHLIGHTED_CODE_COLOR)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\pyprint\Printer.py", line 42, in print
    return self._print(output, **kwargs)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\pyprint\ColorPrinter.py", line 45, in _print
    return self._print_uncolored(output, **kwargs)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\pyprint\ConsolePrinter.py", line 24, in _print_uncolored
    print(output, end="")

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 137, in write
    self.write_and_convert(text)

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 165, in write_and_convert
    self.write_plain_text(text, cursor, len(text))

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\site-packages\colorama\ansitowin32.py", line 170, in write_plain_text
    self.wrapped.write(text[start:end])

  File "c:\users\fabia\appdata\local\programs\python\python35-32\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]

UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 0: character maps to <undefined>

C:\Users\fabia\Downloads\pys>python

**Comment by sils1297** [comment]
@AbdealiJK can you look into this one? We've had another occurrence too:

> One thing I noticed is that all the UTF-8 characters have been replaced in our JSON files -- I'd like for them to stay as-is.

https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2289#issuecomment-184455118

**Comment by sils1297** [comment]
That one is rather https://github.com/coala-analyzer/coala/issues/1527 .

**Comment by AbdealiJK** [comment]
I do not have a windows machine to test - and hence it'd be difficult for me to do this

**Comment by sils1297** [comment]
maybe this can be solved with https://github.com/coala-analyzer/coala/pull/1541#issuecomment-185641603 , @AbdealiJK can you try reproducing this and solving it?

**Comment by AbdealiJK** [comment]
I am able to reproduce the. I opened the files in a hex editor and noticed 4 chars were removed when coala wrote back to it.

The symbol ° is B0 in the file after coala ran on it.
The same thing in the one before coala ran on it is @#Â° - 40 23 C2 B0


ALSO - This happens in git bash too. (Im not sure if it's windows specific anymore)

**Comment by AbdealiJK** [comment]
Changing the writing of the file to `with open(filename, mode='w', encoding='utf-8') as file:` in `coalib.results.result_actions.ApplyPatchAction` (line 50) fixes this

**Comment by Makman2** [comment]
@TimSo94 is the bug solved for you?

**Comment by TimSo94** [comment]
Yes, now it works fine. Thanks! :)
