### ISSUE TITLE
py.test error

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1489]
After running all tests py.test crashes
```
Results (22.35s):
     496 passed
      82 skipped
Traceback (most recent call last):
  File "/usr/local/bin/py.test", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 48, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/main.py", line 115, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/main.py", line 111, in wrap_session
    config._ensure_unconfigure()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/config.py", line 835, in _ensure_unconfigure
    self.hook.pytest_unconfigure(config=self)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/local/lib/python3.4/dist-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/red/soc/coala/conftest.py", line 7, in pytest_unconfigure
    if 'html' in config.option.cov_report and os.path.isfile(htmlcov_path):
AttributeError: 'CmdOptions' object has no attribute 'cov_report'
```

**Comment by AbdealiJK** [comment]
@Redridge can you tell me what command you ran exactly ? `py.test` only ?
Also is this ubuntu ?
Have you installed everything from `test-requirements.txt` ?

**Comment by Redridge** [comment]
I hadn't installed everything from `test-requirements.txt` 
Now it works fine
