### ISSUE TITLE
RadonBear throws exceptions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1577]
```
[DEBUG][15:10:00] The bear RadonBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/prog/coala/coalib/bears/Bear.py", line 97, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/prog/coala/coalib/misc/../../bears/python/RadonBear.py", line 32, in run
    for visitor in radon.complexity.cc_visit("".join(file)):
  File "/usr/lib/python3.5/site-packages/radon/complexity.py", line 93, in cc_visit
    return cc_visit_ast(code2ast(code), **kwargs)
  File "/usr/lib/python3.5/site-packages/radon/visitors.py", line 33, in code2ast
    return ast.parse(source)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 115
    print '[EXTTEST]', msg % args
                    ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by AbdealiJK** [comment]
Duplicate of https://github.com/coala-analyzer/coala/issues/1578

**Comment by sils1297** [comment]
it's not a duplicate, it's another exception.

**Comment by sils1297** [comment]
Both need handling.

**Comment by sils1297** [comment]
ah you want to mov e them together... ok
