### ISSUE TITLE
RadonBear throws exceptions

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1578]
```
[DEBUG][15:10:00] The bear RadonBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/prog/coala/coalib/bears/Bear.py", line 97, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/prog/coala/coalib/misc/../../bears/python/RadonBear.py", line 42, in run
    filename, visitor.lineno, visitor.col_offset, visitor.endline)
  File "/home/lasse/prog/coala/coalib/results/SourceRange.py", line 43, in from_values
    return cls(start, end)
  File "/home/lasse/prog/coala/coalib/misc/Decorators.py", line 298, in decorated
    return function(*args, **kwargs)
  File "/home/lasse/prog/coala/coalib/results/SourceRange.py", line 25, in __init__
    TextRange.__init__(self, start, end)
  File "/home/lasse/prog/coala/coalib/misc/Decorators.py", line 298, in decorated
    return function(*args, **kwargs)
  File "/home/lasse/prog/coala/coalib/results/TextRange.py", line 33, in __init__
    raise ValueError("End position can't be less than start position.")
ValueError: End position can't be less than start position.
```

**Comment by AbdealiJK** [comment]
Another exception:

```
[DEBUG][15:10:00] The bear RadonBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/prog/coala/coalib/bears/Bear.py", line 97, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/prog/coala/coalib/misc/../../bears/python/RadonBear.py", line 32, in run
    for visitor in radon.complexity.cc_visit("".join(file)):
  File "/usr/lib/python3.5/site-packages/radon/complexity.py", line 93, in cc_visit
    return cc_visit_ast(code2ast(code), **kwargs)
  File "/usr/lib/python3.5/site-packages/radon/visitors.py", line 33, in code2ast
    return ast.parse(source)
  File "/usr/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 115
    print '[EXTTEST]', msg % args
                    ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by sils1297** [comment]
This issue was moved to coala-analyzer/coala-bears#19

**Comment by AbdealiJK** [comment]
This issue was moved to coala-analyzer/coala-bears#24
