### ISSUE TITLE
Wrong regex triggers unknown error

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#169]
Traceback (most recent call last):
  File "/usr/bin/coala", line 34, in <module>
    SectionExecutor(section=section, global_bear_list=global_bears, local_bear_list=local_bears).run()
  File "/usr/lib/python3.4/site-packages/coalib/processes/SectionExecutor.py", line 80, in run
    filename_list = FileCollector.from_section(self.section).collect()
  File "/usr/lib/python3.4/site-packages/coalib/collecting/FileCollector.py", line 205, in collect
    files.extend(self._get_files_from_dir(a_dir))
  File "/usr/lib/python3.4/site-packages/coalib/collecting/FileCollector.py", line 155, in _get_files_from_dir
    if os.path.isfile(abs_file) and self._is_target(abs_file):
  File "/usr/lib/python3.4/site-packages/coalib/collecting/FileCollector.py", line 118, in _is_target
    if self._regex != "$" and re.match(self._regex, os.path.split(file_path)[1]):
  File "/usr/lib64/python3.4/re.py", line 156, in match
    return _compile(pattern, flags).match(string)
  File "/usr/lib64/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.4/sre_parse.py", line 746, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.4/sre_parse.py", line 567, in _parse
    raise error("nothing to repeat")
sre_constants.error: nothing to repeat

with 
files_regex = *.c

**Comment by sils1297** [comment]
its a re.error

**Comment by sils1297** [comment]
solved on #177
