### ISSUE TITLE
--bear-dirs does not search recursively

### ISSUE THREAD

**Issue by Redridge** [coala-analyzer/coala#1710]
As stated in the title. I don't know if it is intended or not but I think it should search recursively.

**Comment by Makman2** [comment]
@Redridge could you post your bug output like you have written in gitter? When you don't install coala-bears and try to use them using `--bear-dirs`^^

**Comment by sils1297** [comment]
It should only search recursively if you do `/path/to/dir/**`

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-26 2:52 GMT+01:00 Mischa Krüger <notifications@github.com>:

**Comment by Redridge** [comment]
```
red@red:~/soc/coala-tutorial$ ../coala/coala --bear-dirs=../coala-bears/** --bears=ClangASTPrintBear --files=src/main.c -L DEBUG
[WARNING][11:40:27] The default coafile '.coafile' was not found. Ignoring it.
[WARNING][11:40:27] Unable to collect bears from /home/red/soc/coala-bears/bears/c_languages/codeclone_detection/ClangASTPrintBear.py. Probably the file is malformed or the module code raises an exception.
[DEBUG][11:40:27] Exception was:
Traceback (most recent call last):

  File "/home/red/soc/coala/coalib/collecting/Collectors.py", line 118, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/home/red/soc/coala/coalib/collecting/Collectors.py", line 23, in _import_bears
    types=list):

  File "/home/red/soc/coala/coalib/collecting/Importers.py", line 116, in iimport_objects
    attributes, local):

  File "/home/red/soc/coala/coalib/misc/Decorators.py", line 14, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/home/red/soc/coala/coalib/collecting/Importers.py", line 87, in _iimport_objects
    module = _import_module(file_path)

  File "/home/red/soc/coala/coalib/collecting/Importers.py", line 30, in _import_module
    return __import__(module_name)

  File "/home/red/soc/coala-bears/bears/c_languages/codeclone_detection/ClangASTPrintBear.py", line 3, in <module>
    from bears.c_languages.ClangBear import clang_available

ImportError: No module named 'bears'
[WARNING][11:40:27] No bears were found matching 'ClangASTPrintBear'.
```

**Comment by Redridge** [comment]
It does find the bear but it doesn't resemble the directory hierarchy, thus the import breaks

**Comment by sils1297** [comment]
try putting the glob in double quotes please, otherwise shell expansion might mess up things

**Comment by sils1297** [comment]
oh yeah as mentioned that is intended. Seeing forward to you filing the other two bugs. This is an invalid one then.
