### ISSUE TITLE
LanguageDefinition: Raises FileNotFoundError for c.coalang

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#1792]
Running the following code 
```
from coalib.bearlib.languages.LanguageDefinition import LanguageDefinition

dict = LanguageDefinition("C","C")

print(dict)
```
gives the following error

```
Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev20160226181603-py3.4.egg/coalib/bears/Bear.py", line 97, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/usr/lib/python3.4/site-packages/coala_bears-0.1.0.dev0-py3.4.egg/bears/general/IndentationBear.py", line 30, in run
    settings_dict = LanguageDefinition("c","c")
  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev20160226181603-py3.4.egg/coalib/bearlib/languages/LanguageDefinition.py", line 31, in __init__
    self.lang_dict = ConfParser().parse(filename)[language.lower()]
  File "/usr/lib/python3.4/site-packages/coala-0.4.2.dev20160226181603-py3.4.egg/coalib/parsing/ConfParser.py", line 48, in parse
    with open(input_data, "r", encoding='utf-8') as _file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.4/site-packages/coala-0.4.2.dev20160226181603-py3.4.egg/coalib/misc/../bearlib/languages/definitions/c.coalang'
```
this is a bug
now i think this happens because we use `coalib_root=os.path.join(os.path.dirname(__file__),os.path.pardir)` inside Constants.py i am not sure, maybe somebody can confirm that

**Comment by abhsag24** [comment]
on further investigation, the coalang file is not there in the build? so its not the fault of `coalib_root` may be it isn't copied during the setup?

**Comment by AbdealiJK** [comment]
Actually, I think we need to add the coalang files in `setup.py` as `package_data`

Normally setuptools only copies the .py files in a module. All other types of files need to be added into data_files or package_data
Like how VERSION has been added

**Comment by abhsag24** [comment]
@AbdealiJK yeah it works now, i'll send a PR
