### ISSUE TITLE
Using ResultFilter throws AssertionError

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1951]
CC @fneu , this one's weird

```
127.0.0.1 - - [24/Mar/2016 22:21:10] "GET / HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/src/app/run_coala.py", line 183, in <module>
    main()
  File "/usr/src/app/run_coala.py", line 177, in main
    analyse_commits(git_repo, tempdir, pr)
  File "/usr/src/app/run_coala.py", line 133, in analyse_commits
    results)
  File "/usr/src/app/run_coala.py", line 102, in get_new_results
    old_results[section_name], results[section_name])
  File "/usr/lib/python3.5/site-packages/coalib/results/ResultFilter.py", line 45, in filter_results
    mod_result_diff_dict_dict[m_r]):
  File "/usr/lib/python3.5/site-packages/coalib/results/ResultFilter.py", line 92, in source_ranges_match
    original_result_diff_dict[file_name])
  File "/usr/lib/python3.5/site-packages/coalib/results/Diff.py", line 211, in __add__
    result.delete_line(line_nr)
  File "/usr/lib/python3.5/site-packages/coalib/results/Diff.py", line 224, in delete_line
    linediff.delete = True
  File "/usr/lib/python3.5/site-packages/coalib/results/LineDiff.py", line 57, in delete
    raise AssertionError("A line cannot be changed and deleted "
AssertionError: A line cannot be changed and deleted at the same time.
```

**Comment by sils1297** [comment]
happens with GitMate on https://github.com/sils1297/antbs/commit/148c75591db690d83e3cb2ecb466564ad48bc456

**Comment by sils1297** [comment]
see https://github.com/Antergos/antbs/pull/5 and the test replica https://github.com/sils1297/antbs/pull/3
