### ISSUE TITLE
Not having appdirs crashes coala setup

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#1957]
We use appdirs in our code and it is in install_requires and requirements.txt

We should also be adding appdirs to `setup_requires` also, as our setup.py uses Constants which imports appdirs.
Not sure why it hasn't given an error till now.

**Comment by sebix** [comment]
Running `setup.py` itself requires `appdirs` already installed. Adding it to required dependencies inside `setup.py` does not fix that at all.

Here full a traceback:
```python
$ ./py3/bin/pip install ~/dev/coala/
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/sebastian/dev/coala
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-kkh5u_08-build/setup.py", line 4, in <module>
        from coalib import assert_supported_version
      File "/tmp/pip-kkh5u_08-build/coalib/__init__.py", line 2, in <module>
        from coalib.misc import Constants
      File "/tmp/pip-kkh5u_08-build/coalib/misc/Constants.py", line 4, in <module>
        import appdirs
    ImportError: No module named 'appdirs'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kkh5u_08-build
```

**Comment by sils1297** [comment]
I think we should  move out the TAGS_DIR constant into a function or something so we don't require the `appdirs` module on import, setup.py shouldn't at all depend on that.

**Comment by AbdealiJK** [comment]
I thought `setup_requires` was made for packages required to run setup.py that ?
(Thats what the docs say)

**Comment by sils1297** [comment]
But we shouldn't require it at all because setup.py doesn't need it.

**Comment by sebix** [comment]
> I thought `setup_requires` was made for packages required to run setup.py that ?
(Thats what the docs say)

When interpreting `setup.py` (which has `setup_requires`), the import *has to be* done.

**Comment by sils1297** [comment]
PR available at https://github.com/coala-analyzer/coala/pull/1978

**Comment by sils1297** [comment]
we should backport this and other dep fixes

**Comment by sebix** [comment]
Next stacktrace with commit 98099eee65cd4ec9c41af2240651a51e69ef77a0:
```python
$ ./py3/bin/pip install ~/dev/coala/
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/sebastian/dev/coala
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-kngs028n-build/setup.py", line 17, in <module>
        from coalib.output.dbus.BuildDbusService import BuildDbusService
      File "/tmp/pip-kngs028n-build/coalib/output/dbus/BuildDbusService.py", line 4, in <module>
        from coalib.misc import Constants
      File "/tmp/pip-kngs028n-build/coalib/misc/Constants.py", line 4, in <module>
        import appdirs
    ImportError: No module named 'appdirs'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-kngs028n-build
```

**Comment by sebix** [comment]
Next one:
```python
$ ./py3/bin/pip install ~/dev/coala/
You are using pip version 7.1.0, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Processing /home/sebastian/dev/coala
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-342p0tpl-build/setup.py", line 17, in <module>
        from coalib.output.dbus.BuildDbusService import BuildDbusService
      File "/tmp/pip-342p0tpl-build/coalib/output/dbus/BuildDbusService.py", line 4, in <module>
        from coalib.misc import Constants
      File "/tmp/pip-342p0tpl-build/coalib/misc/Constants.py", line 4, in <module>
        import appdirs
    ImportError: No module named 'appdirs'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-342p0tpl-build
```

**Comment by sils1297** [comment]
You sure you have the right commit? I tested it. Can you do a `git checkout 9e2bc9` and `git clean -dfx`?
