### ISSUE TITLE
Unbound exception in coala

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#1998]
I'm getting

```
[WARNING][11:46:56] Exception ignored in: <bound method Broker.__del__ of <enchant.Broker object at 0x7f7fb3975550>>
[WARNING][11:46:56] Traceback (most recent call last):
[WARNING][11:46:56]   File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 244, in __del__
[WARNING][11:46:56]   File "/usr/lib/python3.4/site-packages/enchant/__init__.py", line 273, in _free
[WARNING][11:46:56] TypeError: 'NoneType' object is not callable
```

at times with the latest release (5.2)

**Comment by Makman2** [comment]
Inside a normal coala run on our repo?

**Comment by sils1297** [comment]
Yes

**Comment by sils1297** [comment]
Can you reproduce?

**Comment by Makman2** [comment]
nope :/
where is the `enchant` module used? :O

**Comment by SanketDG** [comment]
@sils1297 Could you give the command and the full log here?

**Comment by sils1297** [comment]
can't reproduce it anymore :/
