### ISSUE TITLE
coala throws exception

### ISSUE THREAD

**Issue by arafsheikh** [coala-analyzer/coala#2180]
File on which coala was run: http://pastebin.com/S0XHsD3u
coala version: 0.7.0.dev20160522201645

```text
coala -f=com.coala.core/src/com/coala/core/handlers/RemoveMarkers.java -b=CheckstyleBear -L DEBUG
[WARNING][19:38:04] The default coafile '.coafile' was not found. Ignoring it.
[DEBUG][19:38:05] Platform Linux -- Python 3.5.1+, pip 8.1.1, coalib 0.7.0.dev20160522201645
Executing section Default...
[DEBUG][19:38:05] Files that will be checked:
/home/debugger/git/coala-eclipse/com.coala.core/src/com/coala/core/handlers/RemoveMarkers.java
[DEBUG][19:38:05] Running bear CheckstyleBear...
[DEBUG][19:38:05] Running 'java -jar /home/debugger/.local/share/coala-bears/CheckstyleBear/checkstyle.jar -c /home/debugger/.local/share/coala-bears/CheckstyleBear/google.xml /home/debugger/git/coala-eclipse/com.coala.core/src/com/coala/core/handlers/RemoveMarkers.java'

com.coala.core/src/com/coala/core/handlers/RemoveMarkers.java
|  15| [ERROR][19:38:06] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][19:38:06] Exception was:
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/coalib/coala_main.py", line 89, in run_coala
    log_printer=log_printer)

  File "/usr/local/lib/python3.5/dist-packages/coalib/processes/Processing.py", line 635, in execute_section
    log_printer),

  File "/usr/local/lib/python3.5/dist-packages/coalib/processes/Processing.py", line 494, in process_queues
    ignore_ranges)

  File "/usr/local/lib/python3.5/dist-packages/coalib/processes/Processing.py", line 230, in print_result
    file_diff_dict)

  File "/usr/local/lib/python3.5/dist-packages/coalib/output/ConsoleInteraction.py", line 401, in print_results
    color=color)

  File "/usr/local/lib/python3.5/dist-packages/coalib/output/ConsoleInteraction.py", line 332, in print_affected_files
    sourcerange)

  File "/usr/local/lib/python3.5/dist-packages/coalib/output/ConsoleInteraction.py", line 422, in print_affected_lines
    sourcerange)

  File "/usr/local/lib/python3.5/dist-packages/coalib/output/ConsoleInteraction.py", line 187, in print_lines
    tab_dict, FILE_LINES_COLOR, sourcerange.end.column)

  File "/usr/local/lib/python3.5/dist-packages/coalib/output/ConsoleInteraction.py", line 142, in print_spaces_tabs_in_unicode
    tab_count = tab_dict[index]

KeyError: 1
```

**Comment by sils1297** [comment]
@SanketDG this is important and was scheduled for the *last* release. Can you look into this ASAP as it's also related to your code? We shouldn't ship with such bugs. Next release is this week and this needs fixing :/
