### ISSUE TITLE
Crash on importing xml.parsers

### ISSUE THREAD

**Issue by ecsellon** [coala-analyzer/coala#2217]
Problem encountered using Windows 10, Python 3.5.1
The crashing line works in the interactive interpreter. coala hangs and has to be Ctl+c'ed.

```
(python-coala) C:\projects\jsoncpp>coala
[WARNING][13:36:43] The default coafile '.coafile' was not found. Ignoring it.
Executing section Default...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 115, in _main
    prepare(preparation_data)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 226, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "c:\python35\Lib\multiprocessing\spawn.py", line 278, in _fixup_main_from_path
    run_name="__mp_main__")
  File "c:\python35\Lib\runpy.py", line 240, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "c:\python35\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "c:\python35\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\projects\python-coala\Scripts\coala-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "C:\projects\python-coala\lib\site-packages\pkg_resources\__init__.py", line 34, in <module>
    import plistlib
  File "c:\python35\Lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: No module named 'xml.parsers'
Program terminated by user.
```

**Comment by ecsellon** [comment]
coala was installed by building from source with pip3 install -r requirements.txt being run before coala and coala-bears setup.py build/install

**Comment by ecsellon** [comment]
Released version installed from pip worked fine (no xml import error and no lockup). Pre release version installed from pip was unable to do the xml import but did not lockup as it dumped out after several import failures. Output:
```
(python-coala3) C:\projects\jsoncpp>coala
[WARNING][14:15:30] The default coafile '.coafile' was not found. Ignoring it.
Executing section Default...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "c:\projects\python-coala3\lib\site-packages\coalib\processes\BearRunning.py", line 5, in <module>
    from coalib.bears.GlobalBear import GlobalBear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\GlobalBear.py", line 1, in <module>
    from coalib.bears.Bear import Bear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\Bear.py", line 16, in <module>
    from coalib.settings.Section import Section
  File "c:\projects\python-coala3\lib\site-packages\coalib\settings\Section.py", line 6, in <module>
    from coalib.collecting.Collectors import collect_registered_bears_dirs
  File "c:\projects\python-coala3\lib\site-packages\coalib\collecting\Collectors.py", line 3, in <module>
    import pkg_resources
  File "c:\projects\python-coala3\lib\site-packages\pkg_resources\__init__.py", line 34, in <module>
    import plistlib
  File "c:\python35\Lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: No module named 'xml.parsers'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "c:\projects\python-coala3\lib\site-packages\coalib\processes\BearRunning.py", line 5, in <module>
    from coalib.bears.GlobalBear import GlobalBear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\GlobalBear.py", line 1, in <module>
    from coalib.bears.Bear import Bear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\Bear.py", line 16, in <module>
    from coalib.settings.Section import Section
  File "c:\projects\python-coala3\lib\site-packages\coalib\settings\Section.py", line 6, in <module>
    from coalib.collecting.Collectors import collect_registered_bears_dirs
  File "c:\projects\python-coala3\lib\site-packages\coalib\collecting\Collectors.py", line 3, in <module>
    import pkg_resources
  File "c:\projects\python-coala3\lib\site-packages\pkg_resources\__init__.py", line 34, in <module>
    import plistlib
  File "c:\python35\Lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: No module named 'xml.parsers'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "c:\projects\python-coala3\lib\site-packages\coalib\processes\BearRunning.py", line 5, in <module>
    from coalib.bears.GlobalBear import GlobalBear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\GlobalBear.py", line 1, in <module>
    from coalib.bears.Bear import Bear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\Bear.py", line 16, in <module>
    from coalib.settings.Section import Section
  File "c:\projects\python-coala3\lib\site-packages\coalib\settings\Section.py", line 6, in <module>
    from coalib.collecting.Collectors import collect_registered_bears_dirs
  File "c:\projects\python-coala3\lib\site-packages\coalib\collecting\Collectors.py", line 3, in <module>
    import pkg_resources
  File "c:\projects\python-coala3\lib\site-packages\pkg_resources\__init__.py", line 34, in <module>
    import plistlib
  File "c:\python35\Lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: No module named 'xml.parsers'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python35\Lib\multiprocessing\spawn.py", line 106, in spawn_main
    exitcode = _main(fd)
  File "c:\python35\Lib\multiprocessing\spawn.py", line 116, in _main
    self = pickle.load(from_parent)
  File "c:\projects\python-coala3\lib\site-packages\coalib\processes\BearRunning.py", line 5, in <module>
    from coalib.bears.GlobalBear import GlobalBear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\GlobalBear.py", line 1, in <module>
    from coalib.bears.Bear import Bear
  File "c:\projects\python-coala3\lib\site-packages\coalib\bears\Bear.py", line 16, in <module>
    from coalib.settings.Section import Section
  File "c:\projects\python-coala3\lib\site-packages\coalib\settings\Section.py", line 6, in <module>
    from coalib.collecting.Collectors import collect_registered_bears_dirs
  File "c:\projects\python-coala3\lib\site-packages\coalib\collecting\Collectors.py", line 3, in <module>
    import pkg_resources
  File "c:\projects\python-coala3\lib\site-packages\pkg_resources\__init__.py", line 34, in <module>
    import plistlib
  File "c:\python35\Lib\plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
ImportError: No module named 'xml.parsers'
```

**Comment by Makman2** [comment]
it could be that the scope gets messed up, `coala-bears` has a directory called `xml`, maybe that's the cause^^

**Comment by sils1297** [comment]
I'm pretty sure actually, good catch

**Comment by Makman2** [comment]
The collector puts each subdirectory inside the given bear-directories (or the default one) into the python path. Maybe if we remove that behaviour this bug vanishes, so bears need to import relatively to itself or from the given bear root directory :+1:

**Comment by sils1297** [comment]
@Makman2 can you look into this, it's high priority!

If not, let's just rename the XML dir. This needs a fix yesterday and I mean that. We should have fixed that long ago.

@Adrianzatreanu @AbdealiJK please take a look at this and what we tried here, it seems that this is blocking **all windows installations of coala**. We cannot do a release with this.

**Comment by Makman2** [comment]
@ecsellon hey, we should have fixed this issue, want to retry if it works?

**Comment by ecsellon** [comment]
Retried it and it works now. Thank you.

**Comment by jschwarzwalder** [comment]
I retried and had no issues
