### ISSUE TITLE
generate-ordering: Not working

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/coala#2377]
```
>>> file = ["1"]
>>> a = AbsolutePosition(file, 0)
>>> a.line
1
>>> a.column
1
>>> b = SourceRange.from_values("A", 1,1,1,1)
>>> a == b.start.line
False
>>> a<=b.start
False
```
but suprisingly 
```
>>> a>=b.start
True
```

**Comment by fneu** [comment]
I can... more than just confirm:
```python
>>> a > b.start
True
>>> b.start < a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/coala_decorators/decorators.py", line 226, in lt
    raise TypeError("Comparison with unrelated classes is "
TypeError: Comparison with unrelated classes is unsupported.
```

This most likely has to do with `a` being an `AbsolutePosition` and `b.start` being a `SourcePosition`.
While both inherit from `TestPosition`, `SourcePosition` is the only one to have a `file` param and is defined with:

```python
@generate_ordering("file", "line", "column")
class SourcePosition(TextPosition):
```
compared to 
```
@generate_ordering("line", "column")
class TextPosition:
```

If this is not the source of this problem this bug has to be filed against coala_decorators.

**Comment by fneu** [comment]
```python
>>> b.start
<SourcePosition object(file='/home/fabian/devel/coala/A', line=1, column=1) at 0x7f7de98ccac8>
>>> a
<AbsolutePosition object(line=1, column=1) at 0x7f7de98ccb00>
```

**Comment by abhsag24** [comment]
what kind of ordering is required for "file" ? i do think that is actually the source of the problem @fneu

**Comment by fneu** [comment]
well, we have this in decorators:

```python
def generate_ordering(*members):
    """
    Decorator that generates ordering operators for the decorated class based
    on the given member names. All ordering except equality functions will
    raise a TypeError when a comparison with an unrelated class is attempted.
    (Comparisons with child classes will thus work fine with the capabilities
    of the base class as python will choose the base classes comparison
    operator in that case.)
    Note that this decorator modifies the given class in place!
    :param members: A list of members to compare, ordered from high priority to
                    low. I.e. if the first member is equal the second will be
                    taken for comparison and so on. If a member is None it is
                    considered smaller than any other value except None.
    """
    def decorator(cls):
        def lt(self, other):
            if not isinstance(other, cls):
                raise TypeError("Comparison with unrelated classes is "
                                "unsupported.")

            for member in members:
                if getattr(self, member) == getattr(other, member):
                    continue

                if (
                        getattr(self, member) is None or
                        getattr(other, member) is None):
                    return getattr(self, member) is None

                return getattr(self, member) < getattr(other, member)

            return False

        cls.__lt__ = lt
        return total_ordering(generate_eq(*members)(cls))

return decorator
```

`a` inherits it's ordering from `TextPosition`, meaning:

- `if not isinstance(other, cls):` checks for `b.start` to be an instance of `TextPosition`, which a `SourcePosition` is subclassed from
- ` for member in members:` checks for `line` and `column` only (which is good) and finds no difference, `<=` is therefore false.

'b.start' get's a new ordering from being a `SourcePosition`. So if you call it the other way around as I did:

- `if not isinstance(other, cls):` checks for `a` to be an instance of `SourcePosition` which an `AbsolutePosition` is not.
- ` for member in members:` would get `None` as a first member from `a` even if the the comparison would take place, therefore always returning `False` independent of what the result should be.

coming to equality:
```python
def generate_eq(*members):
    """
    Decorator that generates equality and inequality operators for the
    decorated class. The given members as well as the type of self and other
    will be taken into account.
    Note that this decorator modifies the given class in place!
    :param members: A list of members to compare for equality.
    """
    def decorator(cls):
        def eq(self, other):
            if not isinstance(other, cls):
                return False

            return all(getattr(self, member) == getattr(other, member)
                       for member in members)

        def ne(self, other):
            return not eq(self, other)

        cls.__eq__ = eq
        cls.__ne__ = ne
        return cls

return decorator
```

now this actually looks like it *should* work, but maybe there is something faulty with the `cls` being used? maybe if a checks here for `isinstance(other, AbsolutePosition)`, then that returns `False` and since `__lt__` also returns the results is `a > b.start` ?

unfortunately I cannot check out decorators and debug this atm

**Comment by abhsag24** [comment]
But it shouldnt be! line and column are equal right? so they are also less than or equal?
> <= is therefore false.

**Comment by fneu** [comment]
right, `__lt__` returns False, so `<` is false only

**Comment by sils1297** [comment]
@abhsag24 @fneu please triage the issue, it seems important to solve on first sight? (Not that I read it completely.)

**Comment by abhsag24** [comment]
i did a work around on the `IndentationBear` the only Bear that uses these two together right now.

**Comment by sils1297** [comment]
would a fix be much harder than your workaround?

**Comment by AbdealiJK** [comment]
Bump - no labels => it's never going to be found.
Please fix/triage
@fneu Can you debug this now maybe ?

**Comment by aptrishu** [comment]
@fneu @sils @abhsag24 
IMO every comparison other than equality (which should always return False in this case) should emit an error, after all at the top level we are comparing `AbsolutePosition` and `SourcePosition`.
SourcePosition cares about the file while AbsolutePosition has nothing to do with file (It only cares about text and pos).
So, any comparison should not be possible.

**Comment by aptrishu** [comment]
Also I'm getting this output right now.
```Cython
>>> a 
<AbsolutePosition object(line=1, column=1) at 0x7f39efbea5f8> 
>>> b = SourceRange.from_values("A", 1,1,1,1) 
>>> b 
<SourceRange object(start=<SourcePosition object(file='/home/rishus23/coala/coalib/results/A', line=1, column=1) at 0x7f39efbf4780>, end=<SourcePosition object(file='/home/rishus23/coala/coalib/results/A', line=1, column=1) at 0x7f39efbf42b0>) at 0x7f39efb9c358> 
>>> a == b.start 
True 
>>> a<=b.start 
True 
>>> a>=b.start 
True 
>>> a<b.start 
False 
>>> a>b.start 
False
```

**Comment by aptrishu** [comment]
How about we `generate_ordering` for `AbsolutePosition` as well?
