### ISSUE TITLE
Writing Bears docs example not working

### ISSUE THREAD

**Issue by arush0311** [coala-analyzer/coala#2602]
Running the example from here http://coala.readthedocs.io/en/latest/Users/Tutorials/Writing_Bears.html#communicating-with-the-user results in an error like this.

```
Traceback (most recent call last):
  File "/home/freeza/.virtualenvs/coala/lib/python3.4/site-packages/coalib/bears/Bear.py", line 250, in execute
    return [] if result is None else list(result)
  File "/home/freeza/coala_test/bears/CommunicationBear.py", line 20, in run
    file=filename)
  File "/home/freeza/.virtualenvs/coala/lib/python3.4/site-packages/coala_utils/decorators.py", line 341, in decorated
    return function(*args, **kwargs)
TypeError: from_values() got multiple values for argument 'origin'

```

**Comment by Makman2** [comment]
It seems that giving origin again is not needed, that was actually the purpose of using the `self.new result` method over using the Result constructor.

So what needs to be done imo :
Correct the docs not using origin. :+1:

**Comment by sils1297** [comment]
oh right, self.... has it already embedded as a partial func

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala-analyzer.org/ - http://viperdev.io/ - http://gitmate.com/
