### ISSUE TITLE
UnicodeUnicodeEncodeError: 'EncodeError:

### ISSUE THREAD

**Issue by netman92** [coala-analyzer/coala#2691]
Hello, can you plz look on this ?

```
logg/consumer.py
| 133| async[ERROR][15:39:31] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][15:39:31] Exception was:
Traceback (most recent call last):

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/coala_main.py", line 101, in run_coala
    log_printer=log_printer)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/processes/Processing.py", line 700, in execute_section
    log_printer),

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/processes/Processing.py", line 550, in process_queues
    ignore_ranges)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/processes/Processing.py", line 237, in print_result
    file_diff_dict)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/output/ConsoleInteraction.py", line 415, in print_results
    color=color)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/output/ConsoleInteraction.py", line 346, in print_affected_files
    sourcerange)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/output/ConsoleInteraction.py", line 437, in print_affected_lines
    sourcerange)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/coalib/output/ConsoleInteraction.py", line 203, in print_lines
    line[printed_chars:], lexer), end='')

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/pyprint/Printer.py", line 43, in print
    return self._print(output, **kwargs)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/pyprint/ColorPrinter.py", line 41, in _print
    return self._print_uncolored(output, **kwargs)

  File "/Users/stano/proj/work/logg/.tox/fix/lib/python3.5/site-packages/pyprint/ConsolePrinter.py", line 29, in _print_uncolored
    print(output, end="")

UnicodeEncodeError: 'ascii' codec can't encode character '\u2022' in position 19: ordinal not in range(128)
ERROR: InvocationError: '/Users/stano/proj/work/logg/.tox/fix/bin/coala -a -V'
```

logg/consumer.py:133
```python
async def consume():
```

**Comment by sils1297** [comment]
CC @AbdealiJK

**Comment by netman92** [comment]
Well, this issue appears only in some terminal (e.g. PyCharm). Probably issue with charset.

**Comment by AbdealiJK** [comment]
So, this is probably a problem with pyprint rather than coala.
I think pyprint should sanitize the string being printed to the console to suit the encoding of the console.

Something like:
```
    if sys.stdout.encoding:
        output = output.decode(sys.stdout.encoding)
    print(output)
```

@netman92 Would you be interested in testing it and making a Pull Request ?

**Comment by netman92** [comment]
Yes I do. So shoud I create PR here ? https://gitlab.com/coala/PyPrint/ @AbdealiJK

**Comment by AbdealiJK** [comment]
@netman92 Yep

**Comment by netman92** [comment]
I did this https://gitlab.com/coala/PyPrint/merge_requests/7 (note, that it's WIP).

But I dont know how properly mock `sys.stdout` to test it :( @AbdealiJK

**Comment by AbdealiJK** [comment]
@netman92 I believe the best way to mock it would be to mock `sys.stdout` and `sys.stdout.encoding` using the  python [unittest.mock.patch](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch) decorator.

If you have any issues https://gitter.im/coala-analyzer/coala would be a good place to ping us for a realtime discussion

**Comment by sils1297** [comment]
don't we have a decorator or something like this in coala-utils that does this?

**Comment by sils1297** [comment]
see https://gitlab.com/coala/coala-utils/blob/master/coala_utils/ContextManagers.py#L57

**Comment by sils1297** [comment]
ok you can't use coala-utils because coala-utils depends on pyprint!

**Comment by AbdealiJK** [comment]
@sils1297 Mocking is probably a better practice for tests in these cases.
Also, having pyprint depend on coala-utils for a test seems like an overkill

**Comment by netman92** [comment]
Resolved https://gitlab.com/coala/PyPrint/commit/579ba7d747950fa389ea93e1b1456eedc9e3d533

**Comment by sils1297** [comment]
I think we should keep this open until coala uses the new pyprint version, i.e. the upgrading commit can have a fixes with this issue.
