### ISSUE TITLE
show-bears: An unknown error occurred

### ISSUE THREAD

**Issue by martin-kokos** [coala-analyzer/coala#2738]
### Overview Description
Running show bears yields causes unknown error
# Steps to Reproduce

1. `pip3 install coala-bears`
2. `coala --show-bears --filter-by-language python`

# Actual Results
```[ERROR][11:08:24] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:```

# Expected Results
List available bears fro python

# Reproducibility
Steps are reproducible with same result

# Additional Information:
versions:
```
coala==0.8.1
coala-bears==0.8.3
coala-decorators==0.2.1
coala-utils==0.4.9
```

Verbose output:
```
$ coala --show-bears --filter-by-language python -V
[WARNING][11:14:40] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
[WARNING][11:14:40] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][11:14:40] coala will not run any analysis. Did you forget to give the `--bears` argument?
[ERROR][11:14:40] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:
[DEBUG][11:14:40] Exception was:
Traceback (most recent call last):

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)

AttributeError: _DistInfoDistribution__dep_map


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.4/dist-packages/coalib/coala.py", line 39, in main
    args.filter_by_language, log_printer)

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/ConfigurationGathering.py", line 297, in get_filtered_bears
    sections, log_printer)

  File "/usr/local/lib/python3.4/dist-packages/coalib/collecting/Collectors.py", line 253, in collect_all_bears_from_sections
    bear_dirs = sections[section].bear_dirs()

  File "/usr/local/lib/python3.4/dist-packages/coalib/settings/Section.py", line 74, in bear_dirs
    for bear_dir in collect_registered_bears_dirs('coalabears')]

  File "/usr/local/lib/python3.4/dist-packages/coalib/collecting/Collectors.py", line 291, in collect_registered_bears_dirs
    registered_package = ep.load()

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2087, in load
    if require: self.require(env, installer)

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2100, in require
    working_set.resolve(self.dist.requires(self.extras),env,installer)))

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2291, in requires
    dm = self._dep_map

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")

  File "/usr/share/python-wheels/setuptools-3.3-py2.py3-none-any.whl/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]

ValueError: ("Expected ',' or end-of-list in", 'appdirs ==1.*', 'at', '*')
```

**Comment by sils1297** [comment]
I think this is because your setuptools is quite old. Can you try to use a virtualenv? Documentation about this is here: http://docs.coala.io/en/latest/Users/Install.html#installing-inside-a-virtualenv

**Comment by martin-kokos** [comment]
`pip3 install -U setuptools` 3.3 -> 26.1.1 : didn't resolve
`pip3 install -U wheel` 0.24.0 -> 0.29.0 : didn't resolve
`pip3 install -U pip` 1.5.4 -> 8.1.2 : **resolved**

I did not need to reinstall `coala-bears` after updating pip.

**Comment by sils1297** [comment]
Ok I'm marking this usability, we need a better message here.

**Comment by jayvdb** [comment]
This will be fixed by removing use of setuptools / pkg_resources as our plugin loader.  There is an issue about that.

**Comment by jayvdb** [comment]
#3545
