### ISSUE TITLE
StringProcesses.search_in_between() is broken

### ISSUE THREAD

**Issue by smfn3321** [coala-analyzer/coala#415]
The `StringProcesses.search_in_between()` and `StringProcess.unescaped_search_in_between()` functions fail with `sre_constants.error` if the `begin` and/or `end` strings contain parentheses or similar special characters that break the regular expression.

The docstring states:
> :param begin:                The begin-sequence where to start matching.
                                 Providing regexes (and not only fixed strings)
                                 is allowed.
    :param end:                  The end-sequence where to end matching.
                                 Providing regexes (and not only fixed strings)
                                 is allowed.

I would propose to either fix the function in a way that allows all kinds of strings to be passed, or at least change the docstring to:

> ":param begin: The begin-sequence where to start matching. Providing regexes is __required__."

Example 1:
```
>>> from coalib.parsing import StringProcessing as SP
>>> list(SP.search_in_between("(", ")", "a(b)c"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabian/Projekte/coala/coalib/parsing/StringProcessing.py", line 206, in search_in_between
    compiled_begin_pattern = re.compile(begin)
  File "/usr/lib64/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.4/sre_parse.py", line 746, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.4/sre_parse.py", line 696, in _parse
    raise error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis
```
Example 2:
```
>>> list(SP.search_in_between("[", "]", "a[b]c"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabian/Projekte/coala/coalib/parsing/StringProcessing.py", line 206, in search_in_between
    compiled_begin_pattern = re.compile(begin)
  File "/usr/lib64/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.4/sre_parse.py", line 746, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.4/sre_parse.py", line 484, in _parse
    raise error("unexpected end of regular expression")
sre_constants.error: unexpected end of regular expression
```
Note that all is fine if the `begin` and `end` strings are provided as a regular expression:
```
>>> list(SP.search_in_between("[(]", "[)]", "a(b)c"))
['b']
```

**Comment by smfn3321** [comment]
unsure about this one:

```
>>> list(SP.search_in_between("[\\]","[\\]","\\ab\\"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabian/Projekte/coala/coalib/parsing/StringProcessing.py", line 206, in search_in_between
    compiled_begin_pattern = re.compile(begin)
  File "/usr/lib64/python3.4/re.py", line 219, in compile
    return _compile(pattern, flags)
  File "/usr/lib64/python3.4/re.py", line 288, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib64/python3.4/sre_compile.py", line 465, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib64/python3.4/sre_parse.py", line 746, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib64/python3.4/sre_parse.py", line 358, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib64/python3.4/sre_parse.py", line 484, in _parse
    raise error("unexpected end of regular expression")
sre_constants.error: unexpected end of regular expression
```

**Comment by Makman2** [comment]
You are right I need to change the docs. But that behaviour is totally correct, since braces are special characters in regexes (to start capturing groups etc.).
For the second example: Since python also escapes the regex would technically expand to following expression:
`[\]`
and that is an invalid regex sequence. You open a character set but you don't close it. Anyway you should pass raw strings to the functions so you are not confused with double-escaping.
So either `r"[\\]"` or `"[\\\\]"`

**Comment by Makman2** [comment]
I opened an explicit issue for that, see #417.
