### ISSUE TITLE
decoding error while reading linux kernel

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#488]
Seems we have a problem when just loading the files for the linux kernel into memory:

```
lasse@lsmobfd ~/prog/linux-4.0.1 % coala
Executing section Default...
[ERROR][20:01:50] An unknown error occurred. This is a bug. We are sorry for the inconvenience. Please contact the developers for assistance. During execution of coala an exception was raised. This should never happen. When asked for, the following information may help investigating:

Exception was:
Traceback (most recent call last):

  File "/usr/bin/coala", line 47, in <module>
    log_printer=log_printer).run()

  File "/usr/lib/python3.4/site-packages/coalib/processes/SectionExecutor.py", line 88, in run
    processes, arg_dict = self._instantiate_processes(running_processes)

  File "/usr/lib/python3.4/site-packages/coalib/processes/SectionExecutor.py", line 157, in _instantiate_processes
    file_dict = self._get_file_dict(filename_list)

  File "/usr/lib/python3.4/site-packages/coalib/processes/SectionExecutor.py", line 199, in _get_file_dict
    file_dict[filename] = f.readlines()

  File "/usr/lib64/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 931: invalid start byte
coala  33.89s user 0.81s system 99% cpu 34.731 total
```

**Comment by sils1297** [comment]
is happens when parsing the file `linux-4.0.1/lib/fonts/font_8x8.c`.

**Comment by sils1297** [comment]
so we need a design for how we can make files accessible to the bears that contain those chars, e.g. one may want to write a bear that processes binary files.

For now I'm catching this, logging an error and leaving out the file.

**Comment by sils1297** [comment]
heres a patch but without tests yet. if anyone has the time to do this, grab this up:

```
diff --git a/coalib/processes/SectionExecutor.py b/coalib/processes/SectionExecutor.py
index c959ae6..f56313f 100644
--- a/coalib/processes/SectionExecutor.py
+++ b/coalib/processes/SectionExecutor.py
@@ -1,6 +1,7 @@
 import multiprocessing
 import queue
 import threading
+import sys
 
 from coalib.collecting.Collectors import collect_files
 from coalib.collecting import Dependencies
@@ -11,6 +12,7 @@ from coalib.settings.Section import Section
 from coalib.settings.Setting import path_list
 from coalib.output.Interactor import Interactor
 from coalib.output.printers.Printer import Printer
+from coalib.misc.i18n import _
 
 
 def get_cpu_count():
@@ -191,11 +193,21 @@ class SectionExecutor:
         for elem in any_list:
             _queue.put(elem)
 
-    @staticmethod
-    def _get_file_dict(filename_list):
+    def _get_file_dict(self, filename_list):
         file_dict = {}
         for filename in filename_list:
-            with open(filename, "r") as f:
-                file_dict[filename] = f.readlines()
+            try:
+                with open(filename, "r") as f:
+                    file_dict[filename] = f.readlines()
+            except UnicodeDecodeError:
+                self.log_printer.err(_("Failed to read file '{}'. It seems "
+                                       "to contain non-unicode characters. "
+                                       "Leaving it out.".format(filename)))
+            except:
+                self.log_printer.log_exception(_("Failed to read file '{}' "
+                                                 "because of an unknown "
+                                                 "error. Leaving it "
+                                                 "out.").format(filename),
+                                               sys.exc_info()[1])
 
         return file_dict
```
