### ISSUE TITLE
SectionExecutor still fails on Windows

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#550]
Even with the latest Windows patches the `SectionExecutorTest` still fails on my platform:
```
 36/59 | SectionExecutorTest
test_empty_run (__main__.SectionExecutorTest) ... ok
test_process_queues (__main__.SectionExecutorTest) ... ok
test_run (__main__.SectionExecutorTest) ... FAIL

======================================================================
FAIL: test_run (__main__.SectionExecutorTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\MAK\Eigene Dokumente\GitHub\coala\coalib\tests\processes\SectionExecutorTest.py", line 118, in test_run
    results = self.uut.run()
  File ".\coalib\processes\SectionExecutor.py", line 93, in run
    arg_dict["file_dict"]),
  File ".\coalib\processes\SectionExecutor.py", line 152, in _process_queues
    assert control_elem == CONTROL_ELEMENT.GLOBAL_FINISHED
AssertionError

----------------------------------------------------------------------
Ran 3 tests in 2.261s

FAILED (failures=1)
######################################################################
```

**Comment by Makman2** [comment]
Appveyor errored because of this earlier but now the test passes. Mysterious...

**Comment by Makman2** [comment]
Is not windows related but multicore-cpu related. Patch comes in #517.
