### ISSUE TITLE
CloneDetectionBearTest fails on mac

### ISSUE THREAD

**Issue by Udayan12167** [coala-analyzer/coala#620]
```
 5/61 | ClangCloneDetectionBearTest
test_clones (__main__.ClangCloneDetectionBearTest) ... ERROR
test_dependencies (__main__.ClangCloneDetectionBearTest) ... ok
test_invalid_conditions (__main__.ClangCloneDetectionBearTest) ... ok
test_non_clones (__main__.ClangCloneDetectionBearTest) ... ERROR

======================================================================
ERROR: test_clones (__main__.ClangCloneDetectionBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/udayantandon/Documents/gsoc/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 69, in test_clones
    lambda results:
  File "/Users/udayantandon/Documents/gsoc/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 85, in check_clone_detection_bear
    Queue()).run_bear_from_section([], {})
  File "./coalib/bears/Bear.py", line 67, in run_bear_from_section
    **kwargs)
  File "./bears/codeclone_detection/ClangSimilarityBear.py", line 84, in run
    pool = multiprocessing.Pool(get_cpu_count())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/popen_fork.py", line 21, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/popen_fork.py", line 69, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files

======================================================================
ERROR: test_non_clones (__main__.ClangCloneDetectionBearTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/udayantandon/Documents/gsoc/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 59, in test_non_clones
    lambda results:
  File "/Users/udayantandon/Documents/gsoc/coala/bears/tests/codeclone_detection/ClangCloneDetectionBearTest.py", line 85, in check_clone_detection_bear
    Queue()).run_bear_from_section([], {})
  File "./coalib/bears/Bear.py", line 67, in run_bear_from_section
    **kwargs)
  File "./bears/codeclone_detection/ClangSimilarityBear.py", line 84, in run
    pool = multiprocessing.Pool(get_cpu_count())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/context.py", line 118, in Pool
    context=self.get_context())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 150, in __init__
    self._setup_queues()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/pool.py", line 243, in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/context.py", line 111, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/queues.py", line 335, in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
  File "/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/multiprocessing/connection.py", line 520, in Pipe
    fd1, fd2 = os.pipe()
OSError: [Errno 24] Too many open files

----------------------------------------------------------------------
Ran 4 tests in 1.569s

FAILED (errors=2)
[WARNING][16:51:06] Unable to convert condition_list to the desired data type.
######################################################################
```

**Comment by sils1297** [comment]
weird, we may need to do `pool.terminate()` to join all processes explicitly but I'm not sure...

**Comment by Makman2** [comment]
I think I'll set up a VM for a Mac, if we will support this would be a good thing^^

**Comment by sils1297** [comment]
@Udayan12167 can you try to reproduce this on wip/sils/cc ?

**Comment by AbdealiJK** [comment]
Is this still an issue?
Even if it wasn't solved before - I am guessing this is not valid anymore because the `Pool` has been removed.

**Comment by AbdealiJK** [comment]
@Udayan12167 could you confirm ?
