### ISSUE TITLE
Error in windows - process group related

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/coala#754]
```
  4/79 | BuildManPageTest
Exception in thread timeout-killer:
Traceback (most recent call last):
  File "C:\......\lib\threading.py", line 920, in _bootstrap_inner
    self.run()
  File "C:\.......\lib\threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "C:.......\coala-master\coalib\misc\ContextManagers.py", line 45, in kill_it
    os.killpg(pgid, signal.SIGINT)
AttributeError: 'module' object has no attribute 'killpg'

  5/79 | ClangASTPrintBearTest
test_ast (__main__.ClangASTPrintBearTest) ... This test failed because it was taking more than 30.000000 sec to execute. To change t
he timeout setting use the `-T` or `--timeout` argument.
######################################################################
```

**Comment by AbdealiJK** [comment]
Fixed in https://github.com/coala-analyzer/coala/commit/956462c8f97704ae4365c8be86bb44f3bab4fc6e
Closing issue
