### ISSUE TITLE
testing with translation fails

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#848]
Since I installed coala under Windows using gettext (so it installs also translations), Some tests go completely insane:
```
test_print_bears (__main__.ConsoleInteractionTest) ... FAIL
test_print_bears_empty (__main__.ConsoleInteractionTest) ... FAIL
test_print_bears_no_needed_settings (__main__.ConsoleInteractionTest) ... FAIL
test_print_bears_no_optional_settings (__main__.ConsoleInteractionTest) ... ok
test_print_bears_no_sections (__main__.ConsoleInteractionTest) ... ok
test_print_bears_no_settings (__main__.ConsoleInteractionTest) ... ok
test_print_result (__main__.ConsoleInteractionTest) ... ok
test_print_results_empty (__main__.ConsoleInteractionTest) ... ok
test_print_results_for_file (__main__.ConsoleInteractionTest) ... ok
test_print_results_missing_file (__main__.ConsoleInteractionTest) ... ok
test_print_results_missing_line (__main__.ConsoleInteractionTest) ... ok
test_print_results_project_wide (__main__.ConsoleInteractionTest) ... ok
test_print_results_raising (__main__.ConsoleInteractionTest) ... ok
test_print_results_sorting (__main__.ConsoleInteractionTest) ... ok
test_require_settings (__main__.ConsoleInteractionTest) ... ok
test_show_bears (__main__.ConsoleInteractionTest) ... ok
test_static_functions (__main__.ConsoleInteractionTest) ... ok

======================================================================
FAIL: test_print_bears (__main__.ConsoleInteractionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\output\ConsoleInteractionTest.py", line 419, in test_print_bears
    self.assertEqual(expected_string, stdout.getvalue())
AssertionError: "Test[161 chars]ting2: Optional Setting. (Optional, defaults to 'None'.)\n\n" != "Test[161 chars]ting2: Optional Setting. (O
ptional, standardmig 'None'.)\n\n"
  TestBear:
    Test bear Description.

    Benutzt in:
     * default
     * docs

    Bentigte Werte:
     * setting1: Required Setting.

    Optionale Werte:
-    * setting2: Optional Setting. (Optional, defaults to 'None'.)
?                                              -- ^^^^^^^
+    * setting2: Optional Setting. (Optional, standardmig 'None'.)
?                                             ++++  ^^^^^^^



======================================================================
FAIL: test_print_bears_empty (__main__.ConsoleInteractionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\output\ConsoleInteractionTest.py", line 402, in test_print_bears_empty
    self.assertEqual(_("No bears to show."), stdout.getvalue())
AssertionError: 'Es knnen keine Bren gezeigt werden.' != 'Es knnen keine Bren gezeigt werden.\n'
- Es knnen keine Bren gezeigt werden.
+ Es knnen keine Bren gezeigt werden.

?                                       +


======================================================================
FAIL: test_print_bears_no_needed_settings (__main__.ConsoleInteractionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\output\ConsoleInteractionTest.py", line 447, in test_print_bears_no_needed_s
ettings
    self.assertEqual(expected_string, stdout.getvalue())
AssertionError: "Some[136 chars] is an optional setting. (Optional, defaults to 'None'.)\n\n" != "Some[136 chars] is an optional setting. (O
ptional, standardmig 'None'.)\n\n"
  SomeOtherBear:
    This is a Bear.

    Benutzt in:
     * test

    Es werden keine Werte bentigt.

    Optionale Werte:
-    * setting: This is an optional setting. (Optional, defaults to 'None'.)
?                                                        -- ^^^^^^^
+    * setting: This is an optional setting. (Optional, standardmig 'None'.)
?                                                       ++++  ^^^^^^^



----------------------------------------------------------------------
Ran 17 tests in 0.055s

FAILED (failures=3)
[WARNUNG][02:20:45] Eines der Ergebnisse kann nicht ausgegeben werden, da es keine korrekte Ableitung der coala result Klasse ist.
|    |    | [NORMAL] origin:
|    |    | msg
|    |    | [NORMAL] origin:
|    |    | msg
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.Sektion  wird ausgefhrt...
|    |    | [NORMAL] origin:
|    |    | msg
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.|    |    | Bitte geben Sie eine gltige Zahl ein.
|    |    |  0: Tue nichts.
|    |    |  1: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.|    |    | Bitte geben Sie eine gltige Zahl ein.
|    |    |  0: Tue nichts.
|    |    |  1: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.|    |    | Bitte geben Sie einen Wert fr den Parameter 'par
am' (Keine Beschreibung vorhanden.) ein: |    |    | [NORMAL] origin:
|    |    | msg
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.|    |    | Bitte geben Sie einen Wert fr den Parameter 'edi
tor' (The editor to open the file with.) ein: [FEHLER][02:20:45] Failed to execute the action OpenEditorAction.
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.|    |    | [NORMAL] origin:
|    |    | msg
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.[FEHLER][02:20:45] Failed to execute the action OpenEditorAc
tion.
|    |    | Die folgenden Optionen sind fr dieses Ergebnis zutreffend:
|    |    |  0: Tue nichts.
|    |    |  1: Open a temporary clone of the file in an editor.
|    |    |  2: Apply the patch automatically.
|    |    | Bitte geben Sie die Nummer der Aktion ein die ausgefhrt werden soll.←[0;34m

Projektweit:
←[0m[WARNUNG][02:20:45] Eine der bergebenen Einstellungen (0) wurde nicht ordentlich beschrieben.
Bitte geben Sie einen Wert fr die Einstellung "setting" (help text) ein, welche von SomeBear bentigt wird: Bitte geben Sie einen Wert fr die
 Einstellung "setting" (help text) ein, welche von SomeBear und AnotherBear bentigt wird: Bitte geben Sie einen Wert fr die Einstellung "set
ting" (help text) ein, welche von SomeBear, AnotherBear und YetAnotherBear bentigt wird: ###################################################
```

**Comment by Makman2** [comment]
What I already found:
`ConsoleInteractionTest.py`:416
Missing translation of "(Optional, defaults to 'None')"

**Comment by sils1297** [comment]
@Makman2 well a missing translation shouldn't hurt, the tests should use the translated string too

**Comment by sils1297** [comment]
@Makman2 interesting however how this stupid console can't show umlauts...

**Comment by sils1297** [comment]
this is not windows specific
