### ISSUE TITLE
Windows: coala does not like paths with spaces

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala#851]
```
D:\Users\mak\Eigene Dokumente\GitHub\coala [Makman2/lang-fix +3 ~1 -0 !]> .\run_tests.py -t coalaTest
  1/1  | coalaTest
test_find_issues (__main__.coalaTest) ... usage: coala [-h] [-c FILE] [-f FILE [FILE ...]] [-b NAME [NAME ...]]
             [-d DIR [DIR ...]] [-L ENUM] [-S SETTING [SETTING ...]]
             [-B [BOOL]] [-s [FILE]] [-v]
             [TARGETS [TARGETS ...]]
coala: error: unrecognized arguments: Dokumente\GitHub\coala\.coafile"
ERROR
test_find_no_issues (__main__.coalaTest) ... FAIL
test_nonexistent (__main__.coalaTest) ... ok

======================================================================
ERROR: test_find_issues (__main__.coalaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\coalaTest.py", line 65, in test_find_issues
    retval, output = execute_coala_ci("todos -c "+self.coafile)
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\coalaTest.py", line 32, in execute_coala_ci
    retval = coala_ci.main()
  File ".\coalib\coala_ci.py", line 28, in main
    targets) = gather_configuration(lambda *args: True, log_printer)
  File ".\coalib\settings\ConfigurationGathering.py", line 212, in gather_configuration
    sections, targets = load_configuration(arg_list, log_printer)
  File ".\coalib\settings\ConfigurationGathering.py", line 108, in load_configuration
    cli_sections = parse_cli(arg_list=arg_list)
  File ".\coalib\parsing\CliParsing.py", line 46, in parse_cli
    vars(arg_parser.parse_args(arg_list)).items()):
  File "D:\Program Files (x86)\Python 3.4.3\lib\argparse.py", line 1731, in parse_args
    self.error(msg % ' '.join(argv))
  File "D:\Program Files (x86)\Python 3.4.3\lib\argparse.py", line 2386, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "D:\Program Files (x86)\Python 3.4.3\lib\argparse.py", line 2373, in exit
    _sys.exit(status)
SystemExit: 2

======================================================================
FAIL: test_find_no_issues (__main__.coalaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Users\mak\Eigene Dokumente\GitHub\coala\coalib\tests\coalaTest.py", line 61, in test_find_no_issues
    "coala-ci must return zero when running over its "
AssertionError: 255 != 0 : coala-ci must return zero when running over its own code.

----------------------------------------------------------------------
Ran 3 tests in 0.028s
```

**Comment by Makman2** [comment]
the problem is that coala unescapes the backslashes using the StringConverter module. For cli arguments this is not intended^^

**Comment by Makman2** [comment]
Anyway we need to discuss how we parse cli-arguments. Since Linux performs escaping on it's own and others maybe not, we should be careful.
@sils1297 what do you think?

**Comment by Makman2** [comment]
Okay the problem was inproper escaping that occured also from #848.
